name: pr

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Packages
        run: npm install

      - uses: bufbuild/buf-setup-action@v1.27.1
        with:
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate --include-imports

      - name: Lint
        uses: trunk-io/trunk-action@v1
